import type { Recipe } from "./types";

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    title: "Grilled Salmon with Asparagus",
    description: "Fresh salmon fillet with grilled asparagus and lemon butter sauce",
    image: "https://images.unsplash.com/photo-1543992321-cefacfc2322e",
    imageType: "jpg",
    usedIngredientCount: 5,
    missedIngredientCount: 0,
    missedIngredients: [],
    usedIngredients: ["salmon", "asparagus", "lemon", "butter", "garlic"],
    unusedIngredients: [],
    likes: 0,
    servings: 2,
    readyInMinutes: 25,
    instructions: "1. Preheat grill\n2. Season salmon\n3. Grill salmon and asparagus\n4. Make lemon butter sauce",
    summary: "A healthy and delicious grilled salmon dish with fresh asparagus.",
    cuisines: ["Mediterranean"],
    dishTypes: ["main course"],
    diets: ["gluten-free", "low-carb"],
    extendedIngredients: [],
    estimatedCost: 15.99,
    cookingTime: 25,
    dietaryTags: ["gluten-free", "low-carb"]
  },
  {
    id: 2,
    title: "Vegetarian Buddha Bowl",
    description: "Quinoa bowl with roasted vegetables and tahini dressing",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
    imageType: "jpg",
    usedIngredientCount: 5,
    missedIngredientCount: 0,
    missedIngredients: [],
    usedIngredients: ["quinoa", "sweet potato", "chickpeas", "kale", "tahini"],
    unusedIngredients: [],
    likes: 0,
    servings: 2,
    readyInMinutes: 35,
    instructions: "1. Cook quinoa\n2. Roast vegetables\n3. Prepare tahini dressing\n4. Assemble bowl",
    summary: "A nutritious and colorful vegetarian buddha bowl.",
    cuisines: ["Fusion"],
    dishTypes: ["main course"],
    diets: ["vegetarian", "vegan", "gluten-free"],
    extendedIngredients: [],
    estimatedCost: 12.99,
    cookingTime: 35,
    dietaryTags: ["vegetarian", "vegan", "gluten-free"]
  },
  {
    id: 3,
    title: "Chicken Stir-Fry",
    description: "Quick and healthy chicken stir-fry with mixed vegetables",
    image: "https://images.unsplash.com/photo-1625937751876-4515cd8e78bd",
    imageType: "jpg",
    usedIngredientCount: 5,
    missedIngredientCount: 0,
    missedIngredients: [],
    usedIngredients: ["chicken breast", "broccoli", "carrots", "soy sauce", "rice"],
    unusedIngredients: [],
    likes: 0,
    servings: 2,
    readyInMinutes: 20,
    instructions: "1. Cut chicken and vegetables\n2. Cook rice\n3. Stir-fry chicken and vegetables\n4. Add sauce",
    summary: "A quick and healthy chicken stir-fry with fresh vegetables.",
    cuisines: ["Asian"],
    dishTypes: ["main course"],
    diets: ["dairy-free"],
    extendedIngredients: [],
    estimatedCost: 10.99,
    cookingTime: 20,
    dietaryTags: ["dairy-free"]
  }
];

export const ingredientsList = [
  "chicken breast",
  "salmon",
  "quinoa",
  "rice",
  "pasta",
  "broccoli",
  "carrots",
  "asparagus",
  "sweet potato",
  "kale",
  "chickpeas",
  "eggs",
  "milk",
  "cheese",
  "butter",
  "olive oil",
  "soy sauce",
  "garlic",
  "onions",
  "lemon",
  "tomatoes"
];
