import type { Recipe } from "./schema";

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    title: "Grilled Salmon with Asparagus",
    description: "Fresh salmon fillet with grilled asparagus and lemon butter sauce",
    image: "https://images.unsplash.com/photo-1543992321-cefacfc2322e",
    imageType: "jpg",
    usedIngredientCount: 5,
    missedIngredientCount: 0,
    missedIngredients: [],
    usedIngredients: [
      { id: 1, name: "salmon", amount: 200, unit: "g" },
      { id: 2, name: "asparagus", amount: 100, unit: "g" },
      { id: 3, name: "lemon", amount: 1, unit: "" },
      { id: 4, name: "butter", amount: 50, unit: "g" },
      { id: 5, name: "garlic", amount: 2, unit: "cloves" }
    ],
    unusedIngredients: [],
    likes: 0,
    servings: 2,
    readyInMinutes: 25,
    instructions: "1. Preheat grill\n2. Season salmon\n3. Grill salmon and asparagus\n4. Make lemon butter sauce",
    summary: "A healthy and delicious grilled salmon dish with fresh asparagus.",
    cuisines: ["Mediterranean"],
    dishTypes: ["main course"],
    diets: ["gluten-free", "low-carb"],
    extendedIngredients: [],
    estimatedCost: 15.99,
    cookingTime: 25,
    dietaryTags: ["gluten-free", "low-carb"]
  },
  {
    id: 2,
    title: "Vegetarian Buddha Bowl",
    description: "Quinoa bowl with roasted vegetables and tahini dressing",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
    imageType: "jpg",
    usedIngredientCount: 5,
    missedIngredientCount: 0,
    missedIngredients: [],
    usedIngredients: [
      { id: 6, name: "quinoa", amount: 100, unit: "g" },
      { id: 7, name: "sweet potato", amount: 200, unit: "g" },
      { id: 8, name: "chickpeas", amount: 150, unit: "g" },
      { id: 9, name: "kale", amount: 50, unit: "g" },
      { id: 10, name: "tahini", amount: 30, unit: "ml" }
    ],
    unusedIngredients: [],
    likes: 0,
    servings: 2,
    readyInMinutes: 35,
    instructions: "1. Cook quinoa\n2. Roast vegetables\n3. Prepare tahini dressing\n4. Assemble bowl",
    summary: "A nutritious and colorful vegetarian buddha bowl.",
    cuisines: ["Fusion"],
    dishTypes: ["main course"],
    diets: ["vegetarian", "vegan", "gluten-free"],
    extendedIngredients: [],
    estimatedCost: 12.99,
    cookingTime: 35,
    dietaryTags: ["vegetarian", "vegan", "gluten-free"]
  },
  {
    id: 3,
    title: "Chicken Stir-Fry",
    description: "Quick and healthy chicken stir-fry with mixed vegetables",
    image: "https://images.unsplash.com/photo-1625937751876-4515cd8e78bd",
    imageType: "jpg",
    usedIngredientCount: 5,
    missedIngredientCount: 0,
    missedIngredients: [],
    usedIngredients: [
      { id: 11, name: "chicken breast", amount: 250, unit: "g" },
      { id: 12, name: "broccoli", amount: 100, unit: "g" },
      { id: 13, name: "carrots", amount: 100, unit: "g" },
      { id: 14, name: "soy sauce", amount: 30, unit: "ml" },
      { id: 15, name: "rice", amount: 150, unit: "g" }
    ],
    unusedIngredients: [],
    likes: 0,
    servings: 2,
    readyInMinutes: 20,
    instructions: "1. Cut chicken and vegetables\n2. Cook rice\n3. Stir-fry chicken and vegetables\n4. Add sauce",
    summary: "A quick and healthy chicken stir-fry with fresh vegetables.",
    cuisines: ["Asian"],
    dishTypes: ["main course"],
    diets: ["dairy-free"],
    extendedIngredients: [],
    estimatedCost: 10.99,
    cookingTime: 20,
    dietaryTags: ["dairy-free"]
  }
];

export const ingredientsList = [
  "chicken breast",
  "salmon",
  "quinoa",
  "rice",
  "pasta",
  "broccoli",
  "carrots",
  "asparagus",
  "sweet potato",
  "kale",
  "chickpeas",
  "eggs",
  "milk",
  "cheese",
  "butter",
  "olive oil",
  "soy sauce",
  "garlic",
  "onions",
  "lemon",
  "tomatoes"
];
